### ISSUE TITLE
Update to Core 2.7.2

### ISSUE THREAD

**Issue by helmar74** [Jason2866/Portable_VSC_PlatformIO#2]
Hi,

just a simple question:
How can I "Upgrade" to Core 2.7.2 (for the upcoming) 8.4.0 Release?

Why is in platformio.ini mention 2.5.3 ... but 2.7.1 is used for compilation:
```
[core]
; *** Esp8266 Arduino core 2.7.1
platform                  = espressif8266@2.5.3
```

I tried to change 2.5.3 to 2.7.2 but an error occured...

Thanks a lot

**Comment by Jason2866** [comment]
Platformio counting is different from Arduino core number.
You have to use for core 2.7.2
```
[core]
; *** Esp8266 Arduino core 2.7.2
platform                  = espressif8266@2.6.0
```
